policy:
  approval:
    - peer_review


approval_rules:
  - name: peer_review
    requires:
      count: 1
      users: ["xiaotianq", "taoruicui"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
    